"""The production setup file: the class behind each role, and the run, in order.

A project's YAML says which instrument fills each role (``roles:``) and its
params. The setup file says what class each role is — the driver behind it
(``Sim928``), or the proxy for one reached through a server
(``RemoteCounter``) — by narrowing the measurement's ``Resources`` in a
subclass, so an editor follows every role to the code that will run. Its
``__main__`` is the run lifecycle, one visible call per step
(:mod:`lab_wizard.lib.project`).

The roles sit between ``# wizard:roles`` markers, so rebinding a role can
rewrite them without touching anything edited around them.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from lab_wizard.lib.procedures.codegen import class_prefix
from lab_wizard.lib.procedures.spec import python_identifier

__all__ = ["ROLES_BLOCK", "RoleType", "production_setup_source", "roles_block"]

ROLES_BLOCK = "roles"


@dataclass
class RoleType:
    """What the setup declares for one role: the class of its instrument."""

    role: str
    module: str
    name: str
    is_list: bool = False
    # Said beside the field, e.g. where a server's instrument really is.
    note: str = ""


def roles_block(roles: list[RoleType]) -> str:
    """The fields between the ``wizard:roles`` markers: each role and its class."""
    lines = []
    for r in roles:
        annotation = f"list[{r.name}]" if r.is_list else r.name
        lines.append(f"    {r.role}: {annotation}" + (f"  # {r.note}" if r.note else ""))
    return "\n".join(lines)


def production_setup_source(
    *,
    measurement_name: str,
    kind: Literal["procedure", "custom"],
    roles: list[RoleType],
    entry: Literal["measure", "build_procedure"] = "build_procedure",
    has_plots: bool = False,
) -> str:
    """The whole setup file of a production project (unformatted; black it)."""
    name = measurement_name
    imports: set[tuple[str, str]] = {(r.module, r.name) for r in roles}
    if kind == "procedure":
        base = f"measurement.{class_prefix(name)}Resources"
        build = f"measurement.build_{python_identifier(name)}_procedure(resources)"
        definition = ""  # the project's procedure: block, which the module is built from
    else:
        base = "measurement.Resources"
        if entry == "measure":
            imports.add(("lab_wizard.lib.recording", "MeasureStep"))
            build = 'MeasureStep(measurement.measure, resources, name="measure")'
        else:
            build = "measurement.build_procedure(resources)"
        definition = f', definition={{"name": {name!r}, "plots": {"measurement.PLOTS" if has_plots else "[]"}}}'

    fields = roles_block(roles)
    imports |= {
        ("lab_wizard.lib.project", "Project"),
        ("lab_wizard.lib.project", "measurement_module"),
        ("lab_wizard.lib.task_adapters.lifecycle", "RunLifecycle"),
    }
    by_module: dict[str, list[str]] = {}
    for module, item in sorted(imports):
        by_module.setdefault(module, []).append(item)
    lab_wizard_imports = "\n".join(f"from {m} import {', '.join(n)}" for m, n in by_module.items())

    rebuild_note = (
        "\n# Built from the procedure: block of the project YAML, and built again here"
        "\n# whenever that block has changed, so edit the YAML, never the module."
        if kind == "procedure"
        else ""
    )
    return f'''"""
Setup for ``{name}``, generated by lab_wizard.

Which instrument fills each role is in this project's YAML (``roles:``), with
its params and the run's details. What class each role is, is below: follow a
type to the code that will run. Run this file to run the project;
``--remote tcp://host:port`` sends every instrument through one server.
"""

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from lab_procedure import Status

{lab_wizard_imports}

# The measurement, in {name}_measurement.py beside this file. It is loaded by
# its path, never imported by name (project_module.py); the import is only for
# your editor, to follow it to its code.{rebuild_note}
if TYPE_CHECKING:
    import {name}_measurement as measurement
else:
    measurement = measurement_module(Path(__file__).parent)


@dataclass(frozen=True)
class Resources({base}):
    """Each role as the class of the instrument the project YAML binds to it."""

    # wizard:{ROLES_BLOCK}:start
{fields}
    # wizard:{ROLES_BLOCK}:end


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--remote",
        default=None,
        help="Route every instrument through one lab_wizard server (e.g. tcp://lab-server:12300).",
    )
    args = parser.parse_args()

    project = Project.load(Path(__file__).parent, remote=args.remote)

    # Claim the racks this run opens, build each role's instrument (checked
    # against its type above before anything opens), claim the ones on servers,
    # reset them to their baseline, run, put them in their safe state if the run
    # fails, release. See lab_wizard/lib/task_adapters/lifecycle.py.
    status = RunLifecycle(
        claims=project.local_claims(),
        claims_after_resolve=[project.routed_claims],
    ).run(
        resolve=lambda: project.resources(Resources),
        execute=lambda resources: project.run({build}, resources{definition}),
    )
    raise SystemExit(0 if status is Status.SUCCESS else 1)
'''
